# Generated by Django 3.1.3 on 2021-02-01 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espace_perso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('tva', models.FloatField()),
            ],
            options={
                'db_table': 'typeproduit',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('unit', models.BooleanField()),
                ('quantite', models.FloatField()),
                ('unite', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.categorie')),
                ('id_producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espace_perso.producteur')),
            ],
            options={
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.AddField(
            model_name='categorie',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.typeproduit'),
        ),
    ]
