# Generated by Django 3.1.3 on 2021-01-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('info', models.TextField()),
                ('prix', models.FloatField()),
                ('tva', models.FloatField()),
                ('unit', models.BooleanField()),
            ],
            options={
                'db_table': 'typeproduit',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produit_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantite', models.FloatField()),
                ('unite', models.IntegerField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.typeproduit')),
            ],
            options={
                'db_table': 'produit',
            },
        ),
    ]
