# Generated by Django 3.1.3 on 2021-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_typeproduit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduit',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
