# Generated by Django 3.1.3 on 2021-02-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_auto_20210218_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='id_categorie',
            new_name='categorie_id',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='id_type',
            new_name='typeProduit',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='id_produit',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='id_producteur',
            new_name='producteur',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='id_categorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='id_produit',
            new_name='produit_id',
        ),
        migrations.RenameField(
            model_name='typeproduit',
            old_name='id_type',
            new_name='type_id',
        ),
    ]
