# Generated by Django 3.1.4 on 2021-02-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0003_auto_20210219_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('commande_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('statut', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=3, max_digits=8)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('panier_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_personne', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
            options={
                'db_table': 'panier',
            },
        ),
        migrations.CreateModel(
            name='ContenuCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
            options={
                'db_table': 'contenuCommande',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='produit.ContenuCommande', to='produit.Produit'),
        ),
    ]
