# Generated by Django 3.1.3 on 2021-03-02 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0005_auto_20210302_2113'),
        ('produit', '0003_auto_20210219_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Produit',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='Produit',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
