# Generated by Django 3.1.3 on 2021-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_auto_20210302_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priorite',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
