# Generated by Django 3.1.3 on 2021-03-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_auto_20210223_1703'),
        ('produit', '0004_auto_20210302_2113'),
    ]

    operations = [
    ]
