# Generated by Django 3.1.3 on 2021-03-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_auto_20210223_1703'),
        ('produit', '0005_auto_20210315_1800'),
    ]

    operations = [
    ]
