# Generated by Django 3.1.4 on 2021-04-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_auto_20210328_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produit.produit'),
        ),
    ]
