# Generated by Django 3.1.3 on 2021-01-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('mot_de_passe', models.TextField()),
                ('mail', models.TextField()),
                ('num_tel', models.TextField()),
            ],
            options={
                'db_table': 'personne',
            },
        ),
    ]
