# Generated by Django 3.1.3 on 2021-02-17 20:25

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from espace_perso.models import Personne
from django.contrib.contenttypes.models import ContentType


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0001_initial'),
    ]

    operations = [
        
    ]
