# Generated by Django 3.1.3 on 2021-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('mot_de_passe', models.TextField()),
                ('mail', models.TextField()),
                ('num_tel', models.TextField()),
            ],
            options={
                'db_table': 'producteur',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('mot_de_passe', models.TextField()),
                ('mail', models.TextField()),
                ('num_tel', models.TextField()),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
