# Generated by Django 3.1.3 on 2021-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personne',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='personne',
            name='ville',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
