# Generated by Django 3.1.3 on 2021-02-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0002_auto_20210217_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producteur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
    ]
