# Generated by Django 3.1.3 on 2021-02-11 17:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('espace_perso', '0002_auto_20210208_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producteur',
            options={'permissions': [('can_view_espace_perso', 'Peux acceder a la page espace perso')]},
        ),
        migrations.AlterModelManagers(
            name='producteur',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name='producteur',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.AddField(
            model_name='personne',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='personne',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='personne',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.group'),
            preserve_default=False,
        ),
    ]
