# Generated by Django 3.1.3 on 2021-02-11 18:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('espace_perso', '0003_auto_20210211_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('can_view_espace_perso', 'Peux acceder a la page espace perso')]},
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name='producteur',
            old_name='utilisateur',
            new_name='user_prod',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='utilisateur',
            new_name='user_user',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.group'),
            preserve_default=False,
        ),
    ]
