# Generated by Django 3.1.3 on 2021-02-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0003_auto_20210218_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='id_personne',
            new_name='personne_id',
        ),
    ]
