# Generated by Django 3.1.4 on 2021-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_auto_20210223_1703'),
        ('espace_perso', '0004_auto_20210219_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='panier',
            field=models.ManyToManyField(through='produit.Panier', to='produit.Produit'),
        ),
    ]
