# Generated by Django 3.1.3 on 2021-03-02 20:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0004_auto_20210219_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producteur',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='espace_perso.personne')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'producteur',
                'permissions': [('can_view_espace_perso', 'Peux acceder a la page espace perso'), ('can_view_espace_producteur', 'Peux acceder a la page espace producteur')],
                'default_permissions': (),
            },
            bases=('espace_perso.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='espace_perso.personne')),
            ],
            options={
                'db_table': 'utilisateur',
                'permissions': [('can_view_espace_perso', 'Peux acceder a la page espace perso')],
            },
            bases=('espace_perso.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
