# Generated by Django 3.1.3 on 2021-03-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0005_auto_20210302_2113'),
        ('espace_perso', '0005_personne_panier'),
    ]

    operations = [
    ]
