# Generated by Django 3.1.3 on 2021-03-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0005_auto_20210302_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'default_permissions': (), 'permissions': [('can_view_espace_perso', 'Peux acceder a la page espace perso')]},
        ),
        migrations.AddField(
            model_name='personne',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
