# Generated by Django 3.1.4 on 2021-03-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0005_auto_20210302_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'default_permissions': (), 'permissions': [('can_view_espace_perso', 'Peux acceder a la page espace perso')]},
        ),
    ]
