# Generated by Django 3.1.3 on 2021-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0006_auto_20210313_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='confirmation',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='newsletter',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producteur',
            name='iban',
            field=models.CharField(default='TEST 1234', max_length=100),
            preserve_default=False,
        ),
    ]
