# Generated by Django 3.1.3 on 2021-03-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0005_personne_panier'),
        ('espace_perso', '0007_auto_20210315_1800'),
    ]

    operations = [
    ]
