# Generated by Django 3.1.3 on 2021-03-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0009_auto_20210315_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, default=1, to='espace_perso.adresse'),
        ),
    ]
