# Generated by Django 3.1.3 on 2021-03-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0011_auto_20210315_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='espace_perso.adresse'),
        ),
    ]
