# Generated by Django 3.1.3 on 2021-03-28 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0012_auto_20210322_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='adresse',
        ),
        migrations.AddField(
            model_name='adresse',
            name='personne',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='espace_perso.personne'),
            preserve_default=False,
        ),
    ]
