# Generated by Django 3.1.4 on 2021-03-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0014_auto_20210328_2341'),
        ('espace_perso', '0006_auto_20210314_2322'),
    ]

    operations = [
    ]
