# Generated by Django 3.1.4 on 2021-03-29 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0015_merge_20210329_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adresse', to=settings.AUTH_USER_MODEL),
        ),
    ]
