# Generated by Django 3.1.3 on 2021-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_perso', '0015_auto_20210329_1455'),
        ('espace_perso', '0016_auto_20210329_1428'),
    ]

    operations = [
    ]
