# Generated by Django 3.1.4 on 2021-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('message_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('message', models.CharField(max_length=1500)),
            ],
             options={
                'db_table': 'demande',
            }
        ),
    ]
