# Generated by Django 3.1.4 on 2021-03-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espace_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demandes',
            table=None,
        ),
    ]
