# Generated by Django 3.1.4 on 2021-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espace_admin', '0002_auto_20210314_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='objet',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='demandes',
            table='demande',
        ),
    ]
